// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6WFd7XZ9wkS4SM3uecRoRbgnGGA0s2j4',
    appId: '1:936598007627:web:fb2cc367222bab53aa02ce',
    messagingSenderId: '936598007627',
    projectId: 'bitowi',
    authDomain: 'bitowi.firebaseapp.com',
    storageBucket: 'bitowi.firebasestorage.app',
    measurementId: 'G-4N1QLZF69X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1kv2sjNzeeQi2CvkNYeeQt8IiWLiFcr4',
    appId: '1:936598007627:android:c5bfc6d505bda630aa02ce',
    messagingSenderId: '936598007627',
    projectId: 'bitowi',
    storageBucket: 'bitowi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDusHM9j71syjFkJI3F7Q8LdIuJ58n-aE',
    appId: '1:936598007627:ios:831c7778c3c21558aa02ce',
    messagingSenderId: '936598007627',
    projectId: 'bitowi',
    storageBucket: 'bitowi.firebasestorage.app',
    iosBundleId: 'com.example.cryptoAppTask',
  );
}
